//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalystDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustSuppAssociation
    {
        public int ID { get; set; }
        public int refPharmacyID { get; set; }
        public int refSupplierID { get; set; }
        public string AccountNo { get; set; }
        public int InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
    
        public virtual PharmacyMas PharmacyMas { get; set; }
        public virtual SupplierMas SupplierMas { get; set; }
    }
}
